# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '.'
    env:
      - 'PROJECT_ID=${_PROJECT_ID}'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GAR_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_GAR_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_GAR_LOCATION}'
      - '--allow-unauthenticated'
      - '--update-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,GOOGLE_VISION_API_KEY=GOOGLE_VISION_API_KEY:latest'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--timeout=900s'
      - '--min-instances=0'
      - '--max-instances=5'
    env:
      - 'PROJECT_ID=${_PROJECT_ID}'

# --- ADD THIS SECTION ---
options:
  logging: CLOUD_LOGGING_ONLY # Directs all build logs to Cloud Logging

# Substitutions: Define variables that Cloud Build will replace at runtime
substitutions:
  _PROJECT_ID: fridgefeast-466610 # Your GCP Project ID
  _GAR_LOCATION: europe-west3    # The region you chose for your Artifact Registry
  _SERVICE_NAME: fridge-feast-next-app # The name you want for your Cloud Run service
  _REPO_NAME: nextjs-app-repo    # The name of your Artifact Registry repository
  _IMAGE_NAME: fridge-feast-app  # A specific name for the Docker image within your repository

# Optional: Cache node_modules to speed up builds
# caches:
#   - '$PROJECT_ID_REGION-docker.pkg.dev/cloud-builders/npm'
#   paths:
#     - /root/.npm
#     - node_modules